INSERT INTO symbols (code,currency,name,country_flag,created_by,created_date) VALUES 
('AUD',NULL,'Australian Dollar','au',NULL,NULL)
,('BRL',NULL,'Brazilian Real','br',NULL,NULL)
,('CAD',NULL,'Canadian Dollar','ca',NULL,NULL)
,('CHF',NULL,'Swiss Franc','ch',NULL,NULL)
,('CNY',NULL,'Chinese Yuan','cn',NULL,NULL)
,('EUR',NULL,'Euro','eu',NULL,NULL)
,('GBP',NULL,'British Pound Sterling','gb',NULL,NULL)
,('HKD',NULL,'Hong Kong Dollar','hk',NULL,NULL)
,('INR',NULL,'Indian Rupee','in',NULL,NULL)
,('JPY',NULL,'Japanese Yen','jp',NULL,NULL)
,('KRW',NULL,'South Korean Won','kr',NULL,NULL)
,('MXN',NULL,'Mexican Peso','mx',NULL,NULL)
,('NOK',NULL,'Norwegian Krone','no',NULL,NULL)
,('NZD',NULL,'New Zealand Dollar','nz',NULL,NULL)
,('RUB',NULL,'Russian Ruble','ru',NULL,NULL)
,('SEK',NULL,'Swedish Krona','se',NULL,NULL)
,('SGD',NULL,'Singapore Dollar','sg',NULL,NULL)
,('TRY',NULL,'Turkish Lira','tr',NULL,NULL)
,('TWD',NULL,'New Taiwan Dollar','tw',NULL,NULL)
,('USD',NULL,'US Dollar','us',NULL,NULL)
,('ZAR',NULL,'South African Rand','za',NULL,NULL)
,('005930','KRW','Samsung Electronics Co. Ltd.',NULL,NULL,NULL)
,('2354','TWD','Foxconn Technology Co., Ltd.',NULL,NULL,NULL)
,('2498','TWD','HTC Corporation',NULL,NULL,NULL)
,('AAPL','USD','Apple Inc.',NULL,NULL,NULL)
,('AIR','EUR','Airbus Group SE',NULL,NULL,NULL)
,('ALV','EUR','Allianz SE',NULL,NULL,NULL)
,('AMD','USD','Advanced Micro Devices, Inc.',NULL,NULL,NULL)
,('AMZN','USD','Amazon.com, Inc.',NULL,NULL,NULL)
,('ATC','EUR','Altice',NULL,NULL,NULL)
,('ATVI','USD','Activision Blizzard, Inc.',NULL,NULL,NULL)
,('BA','USD','The Boeing Company',NULL,NULL,NULL)
,('BAYN','EUR','Bayer AG',NULL,NULL,NULL)
,('BMW','EUR','Bayerische Motoren Werke Aktiengesellschaft',NULL,NULL,NULL)
,('BN','EUR','Danone',NULL,NULL,NULL)
,('BOL','EUR','Bollore',NULL,NULL,NULL)
,('BZ=F','USD','Brent Crude Oil Last Day Financfuture','oil',NULL,NULL)
,('CA','EUR','Carrefour SA',NULL,NULL,NULL)
,('CMCSA','USD','Comcast Corporation',NULL,NULL,NULL)
,('DIS','USD','The Walt Disney Company',NULL,NULL,NULL)
,('EA','USD','Electronic Arts Inc.',NULL,NULL,NULL)
;

INSERT INTO pair (symbol,name,source,target,exchange,provider_code,created_by,created_date) VALUES 
('BZ=F','Brent Crude Oil Last Day Financfuture','BZ=F','USD','NY Mercantile','YAHOO',NULL,NULL)
,('005930.KS','Samsung Electronics Co. Ltd.','005930','KRW',NULL,'YAHOO',NULL,NULL)
,('2354.TW','Foxconn Technology Co., Ltd.','2354','TWD',NULL,'YAHOO',NULL,NULL)
,('2498.TW','HTC Corporation','2498','TWD',NULL,'YAHOO',NULL,NULL)
,('AAPL','Apple Inc.','AAPL','USD',NULL,'YAHOO',NULL,NULL)
,('AIR.PA','Airbus Group SE','AIR','EUR',NULL,'YAHOO',NULL,NULL)
,('ALV.DE','Allianz SE','ALV','EUR',NULL,'YAHOO',NULL,NULL)
,('AMD','Advanced Micro Devices, Inc.','AMD','USD',NULL,'YAHOO',NULL,NULL)
,('AMZN','Amazon.com, Inc.','AMZN','USD',NULL,'YAHOO',NULL,NULL)
,('ATC.AS','Altice','ATC','EUR',NULL,'YAHOO',NULL,NULL)
,('ATVI','Activision Blizzard, Inc.','ATVI','USD',NULL,'YAHOO',NULL,NULL)
,('BA','The Boeing Company','BA','USD',NULL,'YAHOO',NULL,NULL)
,('BAYN.DE','Bayer AG','BAYN','EUR',NULL,'YAHOO',NULL,NULL)
,('BMW.DE','Bayerische Motoren Werke Aktiengesellschaft','BMW','EUR',NULL,'YAHOO',NULL,NULL)
,('BN.PA','Danone','BN','EUR',NULL,'YAHOO',NULL,NULL)
,('BOL.PA','Bollore','BOL','EUR',NULL,'YAHOO',NULL,NULL)
,('CA.PA','Carrefour SA','CA','EUR',NULL,'YAHOO',NULL,NULL)
,('CMCSA','Comcast Corporation','CMCSA','USD',NULL,'YAHOO',NULL,NULL)
,('DIS','The Walt Disney Company','DIS','USD',NULL,'YAHOO',NULL,NULL)
,('EA','Electronic Arts Inc.','EA','USD',NULL,'YAHOO',NULL,NULL)
;